#lang racket

; Solution to exercise 2.32 of SICP


(define (subsets s)
  (if (null? s)
      (list s)
      (let ((rest (subsets (cdr s))))
        (append rest (map (lambda (x)
                            (cons (car s)
                                  x))
                          rest)))))

(subsets '(1 2 3))

; Explanation
; The Power set of a set can be generated by the following Recursion
; 1. the set of all subsets excluding the first number. 
; 2. the set of all subsets excluding the first number,
; with the first number re-inserted into each subset.
; Power set is the union of set 1 and set 2.